import { describe, expect, it } from "vitest";
import { createMemoryHistory, createRootRoute, createRoute, createRouter } from "@tanstack/react-router";
import { CURRENT_SEASON } from "../lib/seasons.js";
import { RootSearchSchema, TeamsSearchSchema, type TeamsSearch } from "../lib/searchParams.js";

/**
 * 05-05-PLAN.md Task 2's NAV-05/T-05-02 round-trip coverage. Tests the real
 * `RootSearchSchema`/`TeamsSearchSchema` this app's `__root.tsx`/`teams.tsx`
 * actually use — but exercises them through a small, SELF-CONTAINED route
 * tree built with `createRootRoute`/`createRoute` rather than importing the
 * app's own auto-generated `routeTree.gen.ts`. That file is regenerated by
 * `@tanstack/router-plugin` at `vite build`/`vite dev` time and is NOT kept
 * in sync by a plain `vitest run` — depending on it here would make this
 * test's pass/fail depend on whichever build last touched the routes
 * directory, exactly the kind of hidden coupling a deep-link contract test
 * must not have.
 */

describe("RootSearchSchema / TeamsSearchSchema — NAV-05 URL round trip", () => {
  it("a URL string carrying year, algorithm, sort and direction parses to the expected state", () => {
    const params = new URLSearchParams("year=2024&algorithm=epa&sort=hubShift1&sortDir=asc");
    const parsed = TeamsSearchSchema.parse(Object.fromEntries(params));
    expect(parsed).toEqual({ year: 2024, algorithm: "epa", sort: "hubShift1", sortDir: "asc" });
  });

  it("that parsed state serializes back to an equivalent URL", () => {
    const state: TeamsSearch = { year: 2024, algorithm: "epa", sort: "hubShift1", sortDir: "asc" };
    const serialized = new URLSearchParams(state as unknown as Record<string, string>).toString();
    const roundTripped = TeamsSearchSchema.parse(Object.fromEntries(new URLSearchParams(serialized)));
    expect(roundTripped).toEqual(state);
  });

  it("a year outside the known season list is coerced (never accepted raw) rather than reaching a component", () => {
    const parsed = RootSearchSchema.parse({ year: "1999", algorithm: "sigma1" });
    expect(parsed.year).toBe(CURRENT_SEASON);
  });

  it("an unknown algorithm id is coerced (never accepted raw) rather than reaching a component", () => {
    const parsed = RootSearchSchema.parse({ year: "2024", algorithm: "not-a-real-algorithm" });
    expect(parsed.algorithm).toBe("sigma1");
  });

  it("a missing param takes its declared default", () => {
    expect(RootSearchSchema.parse({})).toEqual({ year: CURRENT_SEASON, algorithm: "sigma1" });
    expect(TeamsSearchSchema.parse({})).toEqual({ year: CURRENT_SEASON, algorithm: "sigma1", sort: undefined, sortDir: "desc" });
  });

  it("a param carrying scripting- or path-traversal-shaped text is coerced away for the closed-set fields (year/algorithm/sortDir), never reaching a component as the raw attack string", () => {
    const parsed = RootSearchSchema.parse({
      year: "<script>alert(1)</script>",
      algorithm: "../../../etc/passwd",
    });
    expect(parsed).toEqual({ year: CURRENT_SEASON, algorithm: "sigma1" });

    const teamsParsed = TeamsSearchSchema.parse({ sortDir: "'; DROP TABLE teams; --" });
    expect(teamsParsed.sortDir).toBe("desc");
  });

  it("sort is preserved only as an opaque string — never interpolated into markup or a path anywhere in this schema, only compared for set-membership downstream by resolveSortKey", () => {
    // `sort` has no closed-set constraint (its valid set is season/algorithm
    // dependent — see searchParams.ts's own doc comment), so the schema
    // itself does not reject an adversarial-shaped string; it only ensures
    // the value is a plain string (never an object/array). resolveSortKey.ts
    // is the runtime check that turns an unrecognized key into the total-key
    // fallback before it can ever affect a column lookup.
    const adversarial = "<img src=x onerror=alert(1)>";
    const teamsParsed = TeamsSearchSchema.parse({ sort: adversarial });
    expect(teamsParsed.sort).toBe(adversarial);
    expect(typeof teamsParsed.sort).toBe("string");
  });
});

describe("navigation updater form — untouched params survive a route change (NAV-05)", () => {
  it("preserves year/algorithm/sort/sortDir when navigating with the (prev) => ({ ...prev }) updater form", async () => {
    const rootRoute = createRootRoute({ validateSearch: RootSearchSchema });
    const teamsLikeRoute = createRoute({
      getParentRoute: () => rootRoute,
      path: "/a",
      validateSearch: TeamsSearchSchema,
      component: () => null,
    });
    const otherRoute = createRoute({
      getParentRoute: () => rootRoute,
      path: "/b",
      component: () => null,
    });
    const routeTree = rootRoute.addChildren([teamsLikeRoute, otherRoute]);

    const router = createRouter({
      routeTree,
      history: createMemoryHistory({ initialEntries: ["/a?year=2024&algorithm=epa&sort=hubShift1&sortDir=asc"] }),
    });

    await router.load();
    expect(router.state.location.pathname).toBe("/a");

    // The updater form — spreads `prev` rather than replacing it with an
    // object literal — is the one this plan's own `<prohibitions>` requires
    // (05-05-PLAN.md: "Navigation between routes must NOT replace the search
    // params with an object literal"). This standalone test route tree is
    // NOT the app's registered router (see `main.tsx`'s `Register` module
    // augmentation) — TypeScript's ambient `to`/`search` typing resolves
    // against the app's real routes, not this test's own "/a"/"/b" tree, so
    // an explicit cast is needed here; the runtime behavior under test is
    // unaffected.
    await (router.navigate as (opts: { to: string; search: (prev: Record<string, unknown>) => Record<string, unknown> }) => Promise<void>)({
      to: "/b",
      search: (prev) => ({ ...prev }),
    });
    await router.load();

    const search = router.state.location.search as Record<string, unknown>;
    expect(router.state.location.pathname).toBe("/b");
    expect(search.year).toBe(2024);
    expect(search.algorithm).toBe("epa");
    expect(search.sort).toBe("hubShift1");
    expect(search.sortDir).toBe("asc");
  });
});
