/**
 * Read-only, season-parameterized probe measuring BONUS-RP BASE RATES across
 * a full requested season, for the corpus backfill
 * (`.planning/todos/pending/extend-corpus-2018-2017-2016.md`).
 *
 * Supersedes `recon-rp-rates-2019-2020.ts`, whose committed output
 * (`docs/data/tba-rp-rates-2019-2020.md`) remains the FROZEN record of that
 * 2019/2020 run and is not regenerated by this file. This file exists so
 * that extending reconnaissance to a new season needs no new script file and
 * no edited year literal — only a different `--seasons` argument, e.g.
 * `pnpm recon:rp-rates -- --seasons 2018`.
 *
 * `recon-breakdown-fields.ts` samples a single event to learn the
 * `score_breakdown` SHAPE. This answers a different question that shape
 * alone cannot: how OFTEN does each boolean field actually fire across the
 * FULL season?
 *
 * ## Why every boolean, not a name-matched subset
 *
 * TBA's field naming is NOT stable across FRC eras. 2016's two real bonus
 * RPs (`teleopTowerCaptured`, `teleopDefensesBreached`) are named for the
 * game action, not for the RP — a name filter finds ZERO RPs for 2016 and
 * silently reports an empty table that looks like a successful run. In the
 * other direction, several seasons carry booleans that are prerequisites
 * (`quintetAchieved`, 2022), coopertition markers (`coopertitionCriteriaMet`,
 * 2023/2025), or penalties (`g*Penalty`, 2025) — a name filter would present
 * all of these as ranking points. Both directions are measured facts, not
 * hypotheticals, and 2016 is in this job's declared scope. So this probe
 * enumerates EVERY boolean field it observes and reports each one's base
 * rate; identifying which are genuinely RPs is the human reader's job. This
 * cannot silently miss an RP and cannot invent one.
 *
 * Reads TBA_API_KEY from the environment and sends it only as the
 * X-TBA-Auth-Key header. Never logged, never written to the output document.
 *
 * Run: pnpm recon:rp-rates -- --seasons 2019,2020
 */
import { pathToFileURL } from "node:url";
import {
  deriveOutputPath,
  IN_SEASON_EVENT_TYPES,
  parseReconArgs,
  pctOf,
  tbaApiKey,
  tbaGetOrNull,
  writeReconDoc,
} from "./recon-shared.js";

interface TbaEventSimple {
  key: string;
  name: string;
  event_type: number;
  start_date: string;
}

interface TbaMatch {
  key: string;
  comp_level: string;
  score_breakdown: Record<string, Record<string, unknown>> | null;
}

export type AllianceSide = Record<string, unknown>;

export interface BooleanTallyRow {
  key: string;
  fired: number;
  present: number;
}

/**
 * Walks every alliance-side, records every key whose observed value is a
 * boolean, and accumulates a fired count and a present count per key.
 * Non-boolean fields never appear in the result. Rows come out sorted by
 * key so two runs over the same data render identically.
 */
export function tallyBooleans(sides: readonly AllianceSide[]): BooleanTallyRow[] {
  const byKey = new Map<string, BooleanTallyRow>();
  for (const side of sides) {
    for (const [key, value] of Object.entries(side)) {
      if (typeof value !== "boolean") continue;
      let row = byKey.get(key);
      if (!row) {
        row = { key, fired: 0, present: 0 };
        byKey.set(key, row);
      }
      row.present += 1;
      if (value === true) row.fired += 1;
    }
  }
  return [...byKey.values()].sort((a, b) => a.key.localeCompare(b.key));
}

interface SeasonRates {
  season: number;
  eventsListed: number;
  eventsWithQuals: number;
  qualMatches: number;
  allianceSides: number;
  booleanRows: BooleanTallyRow[];
  /** Observed distribution of the computed `rp` total. */
  rpTotals: Map<number, number>;
}

async function measureSeason(season: number, apiKey: string, eventFilter: string[] | undefined): Promise<SeasonRates> {
  const out: SeasonRates = {
    season,
    eventsListed: 0,
    eventsWithQuals: 0,
    qualMatches: 0,
    allianceSides: 0,
    booleanRows: [],
    rpTotals: new Map(),
  };

  const events = await tbaGetOrNull<TbaEventSimple[]>(`/events/${season}/simple`, apiKey);
  if (!events) return out;

  const eventFilterSet = eventFilter ? new Set(eventFilter) : null;
  const inSeason = events
    .filter((e) => IN_SEASON_EVENT_TYPES.has(e.event_type))
    .filter((e) => (eventFilterSet ? eventFilterSet.has(e.key) : true))
    .sort((a, b) => a.start_date.localeCompare(b.start_date));
  out.eventsListed = inSeason.length;

  const sides: AllianceSide[] = [];

  for (const event of inSeason) {
    const matches = await tbaGetOrNull<TbaMatch[]>(`/event/${event.key}/matches`, apiKey);
    if (!matches) continue;
    const quals = matches.filter((m) => m.comp_level === "qm" && m.score_breakdown != null);
    if (quals.length === 0) continue;
    out.eventsWithQuals += 1;
    out.qualMatches += quals.length;

    for (const match of quals) {
      for (const side of ["red", "blue"] as const) {
        const bd = match.score_breakdown?.[side];
        if (!bd) continue;
        out.allianceSides += 1;
        sides.push(bd);

        const rpVal = bd["rp"];
        if (typeof rpVal === "number") {
          out.rpTotals.set(rpVal, (out.rpTotals.get(rpVal) ?? 0) + 1);
        }
      }
    }
  }

  out.booleanRows = tallyBooleans(sides);
  return out;
}

function render(r: SeasonRates): string {
  const L: string[] = [];
  L.push(`## ${r.season}`);
  L.push("");
  L.push(`- **In-season events listed:** ${r.eventsListed}`);
  L.push(`- **Events that actually played quals:** ${r.eventsWithQuals}`);
  L.push(`- **Qualification matches:** ${r.qualMatches.toLocaleString()}`);
  L.push(`- **Alliance-sides (the denominator below):** ${r.allianceSides.toLocaleString()}`);
  L.push("");
  L.push(`### Boolean field rates`);
  L.push("");
  L.push(
    `Every boolean field observed in \`score_breakdown\` is listed below, not a name-matched`
  );
  L.push(
    `subset — TBA's field naming is not stable across FRC eras, so a name filter would either`
  );
  L.push(
    `silently miss the real RPs (some seasons name them for the game action) or silently`
  );
  L.push(`promote a prerequisite/penalty/coopertition flag to an RP. Identifying which rows below`);
  L.push(`are genuinely ranking points is a human judgment call, not this table's job.`);
  L.push("");
  L.push(`| Flag | Fired | Rate | Present on |`);
  L.push(`|---|---|---|---|`);
  for (const row of r.booleanRows) {
    L.push(`| \`${row.key}\` | ${row.fired.toLocaleString()} | **${pctOf(row.fired, row.present)}** | ${row.present.toLocaleString()} sides |`);
  }
  L.push("");
  L.push(`### Computed \`rp\` total distribution`);
  L.push("");
  L.push(`| RP total | Alliance-sides | Share |`);
  L.push(`|---|---|---|`);
  for (const key of [...r.rpTotals.keys()].sort((a, b) => a - b)) {
    const n = r.rpTotals.get(key)!;
    L.push(`| ${key} | ${n.toLocaleString()} | ${pctOf(n, r.allianceSides)} |`);
  }
  L.push("");
  return L.join("\n");
}

async function main(): Promise<void> {
  const args = parseReconArgs(process.argv.slice(2));
  const apiKey = tbaApiKey();
  const outputPath = deriveOutputPath("recon-rp-rates", args.seasons, args.out);

  const results: SeasonRates[] = [];
  for (const season of args.seasons) {
    console.log(`measuring ${season} (walks every in-season event; this takes a few minutes)...`);
    const r = await measureSeason(season, apiKey, args.events);
    results.push(r);
    console.log(`  ${season}: ${r.qualMatches} quals across ${r.eventsWithQuals}/${r.eventsListed} events`);
  }

  const doc = [
    `# Bonus-RP base rates — ${args.seasons.join(", ")}`,
    ``,
    `Generated by \`scripts/recon-rp-rates.ts\` (\`pnpm recon:rp-rates -- --seasons ${args.seasons.join(",")}\`).`,
    `Read-only; no corpus writes.`,
    ``,
    `Measures how OFTEN every boolean field fires across the FULL season, which the`,
    `single-event shape probe cannot answer. A threshold variable that fires almost never is`,
    `worse than not modelling it at all, so these rates decide what \`rp/rules/{season}.ts\``,
    `should actually model.`,
    ``,
    `Denominator is alliance-sides (2 per qualification match), matching how fields are`,
    `recorded in \`score_breakdown\`.`,
    ``,
    ...results.map(render),
  ].join("\n");

  await writeReconDoc(outputPath, doc, apiKey, args.force);
  console.log(`\nwrote ${outputPath}`);
}

const isEntryPoint = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isEntryPoint) {
  main().catch((err) => {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
}
