/**
 * Read-only, season-parameterized reconnaissance probe over TBA's
 * `score_breakdown` shape for a single sampled event per requested season.
 *
 * Supersedes `recon-tba-fields-2019-2020.ts`, whose committed output
 * (`docs/data/tba-field-recon-2019-2020.md`) remains the FROZEN record of
 * that 2019/2020 run and is not regenerated by this file. This file exists
 * so that extending reconnaissance to a new season (2018, then 2017, then
 * 2016 — see `.planning/todos/pending/extend-corpus-2018-2017-2016.md`)
 * needs no new script file and no edited year literal — only a different
 * `--seasons` argument, e.g. `pnpm recon:fields -- --seasons 2018`.
 *
 * `recon-tba-fields.ts` answers a narrower, already-answered question for
 * 2022-2026 — "does TBA expose a computed per-match RP field?" — and also
 * probed the Statbotics accuracy endpoint (RESEARCH.md Q2). It stays a
 * separate one-shot; folding it in here would mix a historical answered
 * question into a reusable tool, and its committed output
 * (`docs/data/tba-field-recon.md`) is cited elsewhere.
 *
 * Reads TBA_API_KEY from the environment and sends it only as the
 * X-TBA-Auth-Key request header. The key is never logged and never written
 * into the generated document — enforced by `writeReconDoc` in
 * `recon-shared.ts`.
 *
 * Run: pnpm recon:fields -- --seasons 2019,2020
 */
import { pathToFileURL } from "node:url";
import {
  classify,
  deriveOutputPath,
  IN_SEASON_EVENT_TYPES,
  parseReconArgs,
  tbaApiKey,
  tbaGet,
  writeReconDoc,
} from "./recon-shared.js";

/** How many qual matches to sample per season. More than one so a null-in-this-match key is not read as absent. */
const MATCH_SAMPLE_SIZE = 12;
/** How many events to try before giving up on a season. 2020 stopped after ~week 3, so most of its events were never played. */
const MAX_EVENTS_TRIED = 12;

interface TbaEventSimple {
  key: string;
  name: string;
  event_type: number;
  start_date: string;
  week: number | null;
}

interface TbaMatch {
  key: string;
  comp_level: string;
  score_breakdown: Record<string, Record<string, unknown>> | null;
}

/** One observed alliance-side key across the sampled matches. */
interface FieldObservation {
  key: string;
  /** Every distinct runtime type seen (null counted separately from its type). */
  types: Set<string>;
  /** Up to 6 distinct stringified sample values, for reading the domain off directly. */
  samples: Set<string>;
  /** How many of the sampled alliance-sides carried this key at all. */
  presentCount: number;
}

interface SeasonRecon {
  season: number;
  eventsTried: string[];
  eventUsed: { key: string; name: string; week: number | null } | null;
  matchKeys: string[];
  allianceSideCount: number;
  fields: FieldObservation[];
  rpTotalFieldName: string | null;
  error: string | null;
}

async function reconSeason(season: number, apiKey: string, eventFilter: string[] | undefined): Promise<SeasonRecon> {
  const out: SeasonRecon = {
    season,
    eventsTried: [],
    eventUsed: null,
    matchKeys: [],
    allianceSideCount: 0,
    fields: [],
    rpTotalFieldName: null,
    error: null,
  };

  let events: TbaEventSimple[];
  try {
    events = await tbaGet<TbaEventSimple[]>(`/events/${season}/simple`, apiKey);
  } catch (err) {
    out.error = `Could not list events for ${season}: ${err instanceof Error ? err.message : String(err)}`;
    return out;
  }

  const eventFilterSet = eventFilter ? new Set(eventFilter) : null;
  const candidates = events
    .filter((e) => IN_SEASON_EVENT_TYPES.has(e.event_type))
    .filter((e) => (eventFilterSet ? eventFilterSet.has(e.key) : true))
    .sort((a, b) => a.start_date.localeCompare(b.start_date));

  const byKey = new Map<string, FieldObservation>();

  for (const event of candidates.slice(0, MAX_EVENTS_TRIED)) {
    out.eventsTried.push(event.key);
    let matches: TbaMatch[];
    try {
      matches = await tbaGet<TbaMatch[]>(`/event/${event.key}/matches`, apiKey);
    } catch {
      continue;
    }

    const quals = matches
      .filter((m) => m.comp_level === "qm" && m.score_breakdown != null)
      .sort((a, b) => a.key.localeCompare(b.key))
      .slice(0, MATCH_SAMPLE_SIZE);

    if (quals.length === 0) continue;

    out.eventUsed = { key: event.key, name: event.name, week: event.week };

    for (const match of quals) {
      out.matchKeys.push(match.key);
      for (const side of ["red", "blue"] as const) {
        const bd = match.score_breakdown?.[side];
        if (!bd) continue;
        out.allianceSideCount += 1;
        for (const [key, value] of Object.entries(bd)) {
          let obs = byKey.get(key);
          if (!obs) {
            obs = { key, types: new Set(), samples: new Set(), presentCount: 0 };
            byKey.set(key, obs);
          }
          obs.presentCount += 1;
          obs.types.add(classify(value));
          if (obs.samples.size < 6) obs.samples.add(JSON.stringify(value) ?? "undefined");
        }
      }
    }
    break; // one event with real quals is enough
  }

  if (out.eventUsed === null) {
    out.error = `No in-season event with qualification matches carrying score_breakdown found among the first ${Math.min(candidates.length, MAX_EVENTS_TRIED)} candidates.`;
    return out;
  }

  out.fields = [...byKey.values()].sort((a, b) => a.key.localeCompare(b.key));
  out.rpTotalFieldName =
    out.fields.find((f) => f.key.toLowerCase() === "tba_rpearned")?.key ??
    out.fields.find((f) => f.key.toLowerCase() === "rp")?.key ??
    null;
  return out;
}

function renderSeason(r: SeasonRecon): string {
  const lines: string[] = [];
  lines.push(`## ${r.season}`);
  lines.push("");
  if (r.error) {
    lines.push(`**PROBE FAILED:** ${r.error}`);
    lines.push("");
    lines.push(`Events tried: ${r.eventsTried.join(", ") || "(none)"}`);
    lines.push("");
    return lines.join("\n");
  }
  lines.push(`- **Event sampled:** \`${r.eventUsed!.key}\` — ${r.eventUsed!.name} (week ${r.eventUsed!.week ?? "?"})`);
  lines.push(`- **Qual matches sampled:** ${r.matchKeys.length} (${r.allianceSideCount} alliance-sides)`);
  lines.push(`- **Distinct \`score_breakdown\` keys:** ${r.fields.length}`);
  lines.push(
    `- **Computed RP total field:** ${r.rpTotalFieldName ? `\`${r.rpTotalFieldName}\` — PRESENT` : "**ABSENT** — RP totals must be derived from the component fields below"}`
  );
  lines.push("");
  lines.push(`| Key | Type(s) | Present | Observed values |`);
  lines.push(`|---|---|---|---|`);
  for (const f of r.fields) {
    const present = f.presentCount === r.allianceSideCount ? "all" : `${f.presentCount}/${r.allianceSideCount}`;
    const samples = [...f.samples].map((s) => `\`${s.replace(/\|/g, "\\|")}\``).join(", ");
    lines.push(`| \`${f.key}\` | ${[...f.types].join(" \\| ")} | ${present} | ${samples} |`);
  }
  lines.push("");
  return lines.join("\n");
}

async function main(): Promise<void> {
  const args = parseReconArgs(process.argv.slice(2));
  const apiKey = tbaApiKey();
  const outputPath = deriveOutputPath("recon-fields", args.seasons, args.out);

  const results: SeasonRecon[] = [];
  for (const season of args.seasons) {
    console.log(`probing ${season}...`);
    results.push(await reconSeason(season, apiKey, args.events));
  }

  const seasonsLabel = args.seasons.join(", ");
  const doc = [
    `# TBA \`score_breakdown\` reconnaissance — ${seasonsLabel}`,
    ``,
    `Generated by \`scripts/recon-breakdown-fields.ts\` (\`pnpm recon:fields -- --seasons ${args.seasons.join(",")}\`).`,
    `Read-only probe; no corpus writes.`,
    ``,
    `This exists to author \`breakdown/{season}.ts\` and \`rp/rules/{season}.ts\` from`,
    `OBSERVED fields rather than from memory of how a game was scored. Several qual`,
    `matches are sampled per season so a key that is null in one match is not mistaken for an`,
    `absent one.`,
    ``,
    ...results.map(renderSeason),
  ].join("\n");

  await writeReconDoc(outputPath, doc, apiKey, args.force);
  console.log(`\nwrote ${outputPath}`);
  for (const r of results) {
    console.log(
      r.error
        ? `  ${r.season}: FAILED — ${r.error}`
        : `  ${r.season}: ${r.fields.length} keys from ${r.matchKeys.length} matches at ${r.eventUsed!.key}; RP total field ${r.rpTotalFieldName ?? "ABSENT"}`
    );
  }
}

const isEntryPoint = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isEntryPoint) {
  main().catch((err) => {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
}
