/**
 * Read-only, season-parameterized probe that DERIVES bonus-RP thresholds
 * from the data rather than from a game manual, for the corpus backfill
 * (`.planning/todos/pending/extend-corpus-2018-2017-2016.md`).
 *
 * Supersedes `recon-rp-thresholds-2019-2020.ts`, whose committed output
 * (`docs/data/tba-rp-thresholds-2019-2020.md`) remains the FROZEN record of
 * that 2019/2020 run and is not regenerated by this file. This file exists
 * so that extending reconnaissance to a new season needs no new script file
 * and no edited year literal — only a different `--seasons` argument, e.g.
 * `pnpm recon:rp-thresholds -- --seasons 2018`.
 *
 * ## Why derive rather than cite
 *
 * Every `RpRuleModule` returns BOTH a recomputed `bonusFlags` and TBA's own
 * `recordedBonusFlags`, so `reconciliation.test.ts` is a comparison rather
 * than a restatement (D-12). That makes the recomputation rule load-bearing:
 * it is what `predictThresholds` uses for FUTURE matches, where no recorded
 * flag exists. A wrong threshold taken from memory would still reconcile
 * "well enough" to look plausible while quietly mispredicting.
 *
 * ## Why sweep EVERY boolean-against-numeric pair, not a hand-picked list
 *
 * The old per-season `CANDIDATES`/`BOOLEAN_CANDIDATES` records were a
 * hand-picked list of which variables to sweep per season — the last
 * remaining place memory still entered this otherwise-derived process. This
 * probe instead sweeps every observed boolean flag against every observed
 * numeric field (and, separately, against every other observed boolean),
 * per tier, and reports the top `--top` by agreement (default 5; 0 means
 * report every pair). This is strictly better than what it replaces:
 * nothing about which candidates to consider is taken from memory anymore.
 *
 * Reads TBA_API_KEY from the environment, sends it only as X-TBA-Auth-Key,
 * never logs it and never writes it to the output.
 *
 * Run: pnpm recon:rp-thresholds -- --seasons 2019,2020
 */
import { pathToFileURL } from "node:url";
import { deriveOutputPath, EVENT_TYPE_TIERS, parseReconArgs, pctRatio, tbaApiKey, tbaGetOrNull, writeReconDoc } from "./recon-shared.js";

interface TbaEventSimple {
  key: string;
  event_type: number;
  start_date: string;
}
interface TbaMatch {
  key: string;
  comp_level: string;
  score_breakdown: Record<string, Record<string, unknown>> | null;
}

/** One alliance-side observation: the tier, every numeric field, every boolean field. */
export interface Obs {
  tier: string;
  nums: Record<string, number>;
  bools: Record<string, boolean>;
}

async function collect(season: number, apiKey: string, eventFilter: string[] | undefined): Promise<Obs[]> {
  const events = await tbaGetOrNull<TbaEventSimple[]>(`/events/${season}/simple`, apiKey);
  if (!events) return [];

  // EVENT_TYPE_TIERS is this probe's event filter, DELIBERATELY DIFFERENT
  // from IN_SEASON_EVENT_TYPES (the rates probe's filter) because it also
  // admits preseason (100). For 2020 this filter counts 7,640 alliance-sides
  // while IN_SEASON_EVENT_TYPES counts 7,612 for the same season — do not
  // unify these two filters; doing so would silently move every number in
  // both the rp-rates and rp-thresholds committed evidence documents.
  const eventFilterSet = eventFilter ? new Set(eventFilter) : null;
  const inSeason = events
    .filter((e) => EVENT_TYPE_TIERS[e.event_type] !== undefined)
    .filter((e) => (eventFilterSet ? eventFilterSet.has(e.key) : true))
    .sort((a, b) => a.start_date.localeCompare(b.start_date));

  const obs: Obs[] = [];
  for (const event of inSeason) {
    const tier = EVENT_TYPE_TIERS[event.event_type]!;
    const matches = await tbaGetOrNull<TbaMatch[]>(`/event/${event.key}/matches`, apiKey);
    if (!matches) continue;
    for (const m of matches) {
      if (m.comp_level !== "qm" || !m.score_breakdown) continue;
      for (const side of ["red", "blue"] as const) {
        const bd = m.score_breakdown[side];
        if (!bd) continue;
        const nums: Record<string, number> = {};
        const bools: Record<string, boolean> = {};
        for (const [k, v] of Object.entries(bd)) {
          if (typeof v === "number") nums[k] = v;
          else if (typeof v === "boolean") bools[k] = v;
        }
        obs.push({ tier, nums, bools });
      }
    }
  }
  return obs;
}

export interface Sweep {
  flag: string;
  variable: string;
  tier: string;
  n: number;
  bestThreshold: number | null;
  bestAgreement: number;
  flagTrueRate: number;
  /** Agreement you would get by always predicting false — the bar a real rule must beat. */
  trivialAgreement: number;
}

/** Ascending scan over every distinct observed value of `variable`, first-max-wins tie-breaking, same trivial always-false baseline as the season-suffixed predecessor. */
export function sweep(obs: Obs[], flag: string, variable: string, tier: string): Sweep | null {
  const rows = obs.filter((o) => o.tier === tier && flag in o.bools && variable in o.nums);
  if (rows.length === 0) return null;

  const trueCount = rows.filter((r) => r.bools[flag] === true).length;
  const values = [...new Set(rows.map((r) => r.nums[variable]!))].sort((a, b) => a - b);

  let bestThreshold: number | null = null;
  let bestAgreement = -1;
  for (const t of values) {
    let agree = 0;
    for (const r of rows) if ((r.nums[variable]! >= t) === (r.bools[flag] === true)) agree += 1;
    const rate = agree / rows.length;
    if (rate > bestAgreement) {
      bestAgreement = rate;
      bestThreshold = t;
    }
  }

  return {
    flag,
    variable,
    tier,
    n: rows.length,
    bestThreshold,
    bestAgreement,
    flagTrueRate: trueCount / rows.length,
    trivialAgreement: 1 - trueCount / rows.length,
  };
}

/**
 * Sweeps every observed boolean flag against every observed numeric field
 * for the given tier, reporting the top `top` pairs BY AGREEMENT PER FLAG
 * (not globally across flags). `top === 0` means report every pair.
 */
export function sweepCandidates(obs: Obs[], tier: string, top: number): Sweep[] {
  const rowsForTier = obs.filter((o) => o.tier === tier);
  const boolKeys = new Set<string>();
  const numKeys = new Set<string>();
  for (const o of rowsForTier) {
    for (const k of Object.keys(o.bools)) boolKeys.add(k);
    for (const k of Object.keys(o.nums)) numKeys.add(k);
  }

  const results: Sweep[] = [];
  for (const flag of [...boolKeys].sort()) {
    const perFlag: Sweep[] = [];
    for (const variable of [...numKeys].sort()) {
      const s = sweep(obs, flag, variable, tier);
      if (s) perFlag.push(s);
    }
    perFlag.sort((a, b) => b.bestAgreement - a.bestAgreement);
    results.push(...(top === 0 ? perFlag : perFlag.slice(0, top)));
  }
  return results;
}

export interface BoolCheck {
  flag: string;
  predictor: string;
  n: number;
  agreement: number;
  flagTrueRate: number;
  predictorTrueRate: number;
}

export function boolCheck(obs: Obs[], flag: string, predictor: string): BoolCheck | null {
  const rows = obs.filter((o) => flag in o.bools && predictor in o.bools);
  if (rows.length === 0) return null;
  let agree = 0;
  for (const r of rows) if (r.bools[flag] === r.bools[predictor]) agree += 1;
  return {
    flag,
    predictor,
    n: rows.length,
    agreement: agree / rows.length,
    flagTrueRate: rows.filter((r) => r.bools[flag]).length / rows.length,
    predictorTrueRate: rows.filter((r) => r.bools[predictor]).length / rows.length,
  };
}

/**
 * For every observed boolean flag, checks every OTHER observed boolean as a
 * candidate predictor and reports the top `top` by agreement per flag.
 * `top === 0` means report every pair. Not tier-scoped, matching the
 * season-suffixed predecessor's boolean-predictor checks.
 */
export function boolCheckCandidates(obs: readonly Obs[], top: number): BoolCheck[] {
  const boolKeys = new Set<string>();
  for (const o of obs) for (const k of Object.keys(o.bools)) boolKeys.add(k);
  const keys = [...boolKeys].sort();

  const results: BoolCheck[] = [];
  for (const flag of keys) {
    const perFlag: BoolCheck[] = [];
    for (const predictor of keys) {
      if (predictor === flag) continue;
      const r = boolCheck([...obs], flag, predictor);
      if (r) perFlag.push(r);
    }
    perFlag.sort((a, b) => b.agreement - a.agreement);
    results.push(...(top === 0 ? perFlag : perFlag.slice(0, top)));
  }
  return results;
}

const TIERS = ["base", "districtChampionship", "championship"] as const;

function render(season: number, obs: Obs[], top: number): string {
  const L: string[] = [`## ${season}`, ``, `${obs.length.toLocaleString()} alliance-sides across every in-season qualification match.`, ``];

  L.push(`### Threshold sweeps`, ``);
  L.push(`Every observed boolean flag is swept against every observed numeric field, per tier —`);
  L.push(`not a hand-picked candidate list. \`bestThreshold\` is the cut point maximising agreement`);
  L.push(`with TBA's own recorded flag. \`trivial\` is the agreement from always predicting false —`);
  L.push(`a rule must beat it to be worth anything. Top ${top === 0 ? "all" : top} per flag per tier by agreement.`, ``);
  L.push(`| Recorded flag | Candidate variable | Tier | n | Best \`>=\` | Agreement | Trivial | Flag rate |`);
  L.push(`|---|---|---|---|---|---|---|---|`);
  for (const tier of TIERS) {
    for (const s of sweepCandidates(obs, tier, top)) {
      const beats = s.bestAgreement > s.trivialAgreement ? "" : " ⚠";
      L.push(
        `| \`${s.flag}\` | \`${s.variable}\` | ${s.tier} | ${s.n.toLocaleString()} | ${s.bestThreshold} | **${pctRatio(s.bestAgreement)}**${beats} | ${pctRatio(s.trivialAgreement)} | ${pctRatio(s.flagTrueRate)} |`
      );
    }
  }
  L.push(``);

  L.push(`### Boolean predictor checks`, ``);
  L.push(`Every observed boolean is checked as a candidate exact predictor of every other observed`);
  L.push(`boolean. Top ${top === 0 ? "all" : top} per flag by agreement.`, ``);
  L.push(`| Recorded flag | Candidate predictor | n | Agreement | Flag rate | Predictor rate |`);
  L.push(`|---|---|---|---|---|---|`);
  for (const r of boolCheckCandidates(obs, top)) {
    L.push(`| \`${r.flag}\` | \`${r.predictor}\` | ${r.n.toLocaleString()} | **${pctRatio(r.agreement)}** | ${pctRatio(r.flagTrueRate)} | ${pctRatio(r.predictorTrueRate)} |`);
  }
  L.push(``);
  return L.join("\n");
}

async function main(): Promise<void> {
  const args = parseReconArgs(process.argv.slice(2));
  const apiKey = tbaApiKey();
  const outputPath = deriveOutputPath("recon-rp-thresholds", args.seasons, args.out);
  const top = args.top ?? 5;

  const sections: string[] = [];
  for (const season of args.seasons) {
    console.log(`collecting ${season} (walks every in-season event)...`);
    const obs = await collect(season, apiKey, args.events);
    console.log(`  ${season}: ${obs.length} alliance-sides`);
    sections.push(render(season, obs, top));
  }

  const doc = [
    `# Derived bonus-RP thresholds — ${args.seasons.join(", ")}`,
    ``,
    `Generated by \`scripts/recon-rp-thresholds.ts\` (\`pnpm recon:rp-thresholds -- --seasons ${args.seasons.join(",")}\`).`,
    `Read-only; no corpus writes.`,
    ``,
    `Each \`RpRuleModule\` must RECOMPUTE its bonus flags from threshold variables, because`,
    `\`predictThresholds\` sees only threshold-variable values and never a raw breakdown — a module`,
    `that merely echoed TBA's recorded flag could score history but could not predict a match.`,
    `That makes the recomputation rule load-bearing, so these thresholds are DERIVED from every`,
    `observed alliance-side rather than cited from a game manual. Candidate pairs are found by`,
    `sweeping every observed boolean against every observed numeric field (and every other`,
    `boolean), not from a hand-picked list per season.`,
    ``,
    ...sections,
  ].join("\n");

  await writeReconDoc(outputPath, doc, apiKey, args.force);
  console.log(`\nwrote ${outputPath}`);
}

const isEntryPoint = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isEntryPoint) {
  main().catch((err) => {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
}
